repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.9.10"  # Use the latest stable version (check for updates)
    hooks:
      - id: ruff
        args: ["--fix"]

      - id: ruff-format    # Auto-formats code (like `black`)
        args: ["."]
