name: Setup Environment
description: 'Common setup steps: checkout code, restore artifacts, and configure Poetry'
inputs:
  venvArtifactName:
    description: 'Name of the artifact for the virtual environment'
    required: true
  poetryCacheArtifactName:
    description: 'Name of the artifact for the Poetry cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download .venv artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.venvArtifactName }}
        path: ${{ github.workspace }}/.venv

    - name: Download Poetry cache artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.poetryCacheArtifactName }}
        path: /home/runner/.local

    - name: Add Poetry to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Fix Poetry permissions
      run: |
        chmod +x $HOME/.local/bin/poetry
        chmod -R +x $HOME/.local/share/pypoetry/venv/bin/
      shell: bash

    - name: Fix virtual environment permissions
      run: chmod -R +x ${{ github.workspace }}/.venv/bin
      shell: bash
