# .github/actions/run-container-scan/action.yml
name: 'Run Container Scan'
description: 'Runs Trivy vulnerability scan on a specified container image'
inputs:
  image-ref:
    description: 'Full reference to the container image to scan (e.g., registry/repo:tag)'
    required: true
  severity:
    description: 'Comma-separated list of severities to fail on'
    required: false
    default: 'CRITICAL,HIGH'
  exit-code:
    description: 'Exit code for Trivy scan failure'
    required: false
    default: '1' # Fail the step if vulnerabilities found
  sarif-report-path:
    description: 'Output path for the SARIF report'
    required: false
    default: 'trivy-results.sarif'
  artifact-name:
    description: 'Name for the SARIF report artifact'
    required: false
    default: 'trivy-scan-report'

runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image-ref }}
        severity: ${{ inputs.severity }}
        exit-code: ${{ inputs.exit-code }}
        format: 'sarif'
        output: ${{ inputs.sarif-report-path }}

    - name: Upload Trivy SARIF report artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.sarif-report-path }}
        retention-days: 7

    # Also upload to GitHub Security tab
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      # Run this step even if Trivy fails (exit-code=1) to ensure report is uploaded
      if: success() || failure()
      with:
        sarif_file: ${{ inputs.sarif-report-path }}