name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use the same version as your local environment

      # Install Poetry
      - name: Install Poetry
        run: pip install poetry

      # Install Dependencies
      - name: Install Dependencies
        run: poetry install

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD:$PWD/config" >> $GITHUB_ENV


      - name: Run Migrations
        run: poetry run python config/manage.py migrate

      - name: Debug Environment
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          echo "DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE"
          ls -R
          
      - name: Debug Python Path
        run: |
          python -c "import sys; print(sys.path)"  


      # Run Tests
      - name: Run Tests
        run: poetry run pytest

