name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "2.0.1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install Poetry
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=${{ env.POETRY_VERSION }} python3 -

      # Install Dependencies
      - name: Install Dependencies
        run: poetry install

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD:$PWD/config" >> $GITHUB_ENV


      - name: Run Migrations
        run: poetry run python config/manage.py migrate

      # Cache Poetry Dependencies (Plan B)
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-
            
      # Cache .venv for Fastest Installs (Best Plan)
      - name: Cache .venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Debug Environment
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          echo "DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE"
          ls -R
          
      - name: Debug Python Path
        run: |
          python -c "import sys; print(sys.path)"  


      # Run Tests
      - name: Run Tests with Coverage
        run: poetry run pytest

