name: Dependabot Auto-Label

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  label_dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add Label for Production Dependencies
        if: steps.metadata.outputs.dependency-type == 'direct:production'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "production"

      - name: Add Label for Patch Updates
        if: contains(steps.metadata.outputs.update-type, 'semver-patch')
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "patch update"
